import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, type LegalSection } from "@/components/site/LegalPage";
import privacyHero from "@/assets/legal/privacy-hero.webp";

const controllerDetails = [
  ["Registered legal business name", "[REGISTERED LEGAL BUSINESS NAME]"],
  ["Trading name", "[TRADING NAME]"],
  ["Company registration number", "[COMPANY REGISTRATION NUMBER]"],
  ["Registered address", "[REGISTERED ADDRESS]"],
  ["Privacy contact email", "[PRIVACY CONTACT EMAIL]"],
  ["Privacy contact phone", "[PRIVACY CONTACT PHONE]"],
  ["Effective date", "[EFFECTIVE DATE]"],
] as const;

const sections: LegalSection[] = [
  {
    id: "controller",
    title: "Who controls your data",
    content: (
      <>
        <p>
          The organisation identified below is the data controller for personal data processed
          through this website. It decides why and how that information is used.
        </p>
        <dl className="grid gap-3 rounded-2xl border border-line bg-sage/45 p-5 sm:grid-cols-2">
          {controllerDetails.map(([label, value]) => (
            <div key={label}>
              <dt className="type-label text-ink/52">{label}</dt>
              <dd className="mt-1 break-words font-semibold text-ink">{value}</dd>
            </div>
          ))}
        </dl>
      </>
    ),
  },
  {
    id: "scope",
    title: "Scope of this policy",
    content: (
      <>
        <p>
          This policy explains how personal data is handled when you browse the Healthy Pet
          Veterinary Clinic website, view published content and the clinic map, or choose to contact
          the clinic through a telephone, email, WhatsApp, or third-party link.
        </p>
        <p>
          The website does not accept appointment bookings, payments, purchases, or public form
          submissions. Information given directly to the clinic during veterinary care may be
          covered by additional clinical-record and professional obligations outside this website.
        </p>
      </>
    ),
  },
  {
    id: "data-collected",
    title: "Information we process",
    content: (
      <ul>
        <li>
          <strong>Technical and security data:</strong> IP address, browser and device information,
          requested pages, timestamps, basic diagnostics, and security logs generated by the website
          and its hosting providers.
        </li>
        <li>
          <strong>Contact information:</strong> information you voluntarily provide when you call,
          email, or message the clinic. These communications occur outside the public website.
        </li>
        <li>
          <strong>Website preferences:</strong> a browser storage value remembering whether you
          accepted the sensitive-content warning on the Cases page.
        </li>
        <li>
          <strong>Administrator data:</strong> authorised administrator identity, authentication
          session, content changes, and security audit information. This does not apply to ordinary
          public visitors.
        </li>
        <li>
          <strong>Third-party map data:</strong> OpenStreetMap may receive technical information
          when the embedded clinic map loads. Google may receive information if you open the
          external map link.
        </li>
      </ul>
    ),
  },
  {
    id: "purposes",
    title: "Purposes and legal bases",
    content: (
      <>
        <p>We process personal data only when a lawful basis applies:</p>
        <ul>
          <li>
            To deliver, maintain, secure, and troubleshoot the website based on our legitimate
            interests in operating a reliable and secure online presence.
          </li>
          <li>
            To respond when you contact the clinic, based on steps taken at your request, the
            provision of veterinary services, or our legitimate interest in answering enquiries.
          </li>
          <li>
            To meet legal, regulatory, accounting, professional, or dispute-handling obligations
            where processing is required by law or necessary to establish or defend legal claims.
          </li>
          <li>To display the clinic location using an embedded map.</li>
        </ul>
        <p>We do not use website data for automated decision-making or profiling.</p>
      </>
    ),
  },
  {
    id: "sharing",
    title: "Sharing and service providers",
    content: (
      <>
        <p>
          Personal data may be processed by providers that help operate the website, including
          Vercel for hosting and delivery and Supabase for website content, administrator
          authentication, database services, and protected media storage. Providers act under their
          own terms and, where applicable, data-processing arrangements.
        </p>
        <p>
          OpenStreetMap may receive technical information when the embedded map loads. Google Maps,
          WhatsApp/Meta, telephone and email providers, Wolt, Foody, and social-media services may
          receive information when you open or use their services. Their own privacy notices apply.
          We may also disclose information to professional advisers, regulators, courts,
          law-enforcement bodies, or other authorities when legally required.
        </p>
        <p>We do not sell personal data.</p>
      </>
    ),
  },
  {
    id: "transfers",
    title: "International transfers",
    content: (
      <p>
        Some technology providers may process information outside Cyprus or the European Economic
        Area. Where required, transfers must rely on a European Commission adequacy decision,
        approved contractual safeguards such as Standard Contractual Clauses, or another lawful
        transfer mechanism. You may contact us for information about the safeguards relevant to your
        data.
      </p>
    ),
  },
  {
    id: "cookies",
    title: "Cookies and browser storage",
    content: (
      <>
        <p>
          The public website does not currently use advertising or behavioural-analytics cookies. It
          uses limited browser storage to remember acceptance of the Cases sensitive-content
          warning. Authorised administrators also require authentication and interface-preference
          storage to use the protected dashboard.
        </p>
        <p>
          The embedded OpenStreetMap map loads with the Contact section and may use its own
          technologies under its privacy terms. Google Maps and other external services opened
          through links may do the same under their own policies. You can clear local storage and
          cookies through your browser settings; doing so may reset saved preferences or sign an
          administrator out.
        </p>
      </>
    ),
  },
  {
    id: "media",
    title: "Gallery and veterinary case media",
    content: (
      <>
        <p>
          The site may contain clinic, animal, gallery, and veterinary case images. Sensitive case
          images are protected by a warning and are blurred until a visitor chooses to view them.
          These interface controls reduce accidental exposure but do not replace the clinic's duty
          to have a valid legal basis and appropriate permission before publication.
        </p>
        <p>
          If an image or description identifies you, relates to your rights, or you believe it
          should not be available, contact us using the privacy details above. We will review the
          request and restrict or remove content where required. Veterinary information about an
          animal may also constitute personal data when it can be linked to an identifiable person.
        </p>
      </>
    ),
  },
  {
    id: "retention",
    title: "How long we keep information",
    content: (
      <>
        <p>
          We retain personal data only for as long as necessary for the purpose for which it was
          collected, including applicable legal, professional, security, accounting, and claims
          requirements. Retention periods depend on the type of information and the relevant legal
          obligation.
        </p>
        <ul>
          <li>Technical and security logs are kept for the period configured by our providers.</li>
          <li>Direct enquiries are kept while needed to respond and manage any related service.</li>
          <li>
            Administrator accounts and audit records are kept while required for access control,
            security, and accountability.
          </li>
          <li>The sensitive-content preference remains in your browser until you clear it.</li>
          <li>
            Published website content remains available until it is unpublished, archived, or
            removed.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "rights",
    title: "Your data-protection rights",
    content: (
      <>
        <p>
          Subject to the conditions and exceptions in applicable law, you may request access to,
          correction of, erasure of, or restriction of your personal data. You may also object to
          certain processing, request data portability where applicable, and withdraw consent at any
          time where processing relies on consent. Withdrawal does not affect earlier lawful
          processing.
        </p>
        <p>
          To exercise a right, contact us using the privacy details above. We may need to verify
          your identity and will respond within the period required by law. You may also lodge a
          complaint with the{" "}
          <a href="https://www.dataprotection.gov.cy/" target="_blank" rel="noreferrer">
            Office of the Commissioner for Personal Data Protection of Cyprus
          </a>
          , or another competent supervisory authority.
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "Security",
    content: (
      <p>
        We use reasonable technical and organisational measures designed to protect personal data,
        including restricted administrator access, authentication, access-control policies, private
        delivery of sensitive case media, validation, and secure hosting practices. No internet
        service can guarantee absolute security. Please do not send unnecessary sensitive
        information through ordinary email or messaging services.
      </p>
    ),
  },
  {
    id: "children",
    title: "Children",
    content: (
      <p>
        This website is intended for people seeking information about veterinary services and is not
        directed at children. A parent or guardian who believes a child has provided personal data
        should contact us so it can be reviewed and, where appropriate, removed.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes and contact",
    content: (
      <>
        <p>
          We may update this policy when the website, our providers, or legal requirements change.
          The effective date above will be revised when a material update is published.
        </p>
        <p>
          Questions, rights requests, and privacy concerns should be sent to
          <strong> [PRIVACY CONTACT EMAIL]</strong> or <strong>[PRIVACY CONTACT PHONE]</strong>.
        </p>
      </>
    ),
  },
];

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy | Healthy Pet Veterinary Clinic" },
      {
        name: "description",
        content: "How Healthy Pet Veterinary Clinic handles personal data and website privacy.",
      },
      { name: "robots", content: "noindex, nofollow" },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      intro="This policy explains what information is processed through this website, why it is used, and the choices and rights available to you."
      heroImage={privacyHero}
      sections={sections}
    />
  );
}
